Feature/sample06
ivanklesic/Magento_Training pull request #6
Opened 2021-09-07 07:02 UTC by ivanklesic

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Questions or comments

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

2021-09-07 10:13 UTC, tnikcevs requested changes

2021-09-07 10:13 UTC, tnikcevs commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +        foreach ($collection as $block) {
nemoze li se zvati na $collection->delete() ?

btw ovo $block mi negovori baš o čemu se radi, nepiše na klasi description i u poruci je "records", ako se radi o postcodesima treba napisat tako da bude prije jasnije bez velikog upoznavanja konteksta

2021-09-09 12:33 UTC, ivanmatozan requested changes

2021-09-09 12:33 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/view/adminhtml/ui_component/cms_page_form.xml
> +-->
uvijek makni ove Magento copyright komentare u custom kodu

2021-09-09 12:33 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/view/adminhtml/layout/cms_page_edit.xml
> +<?xml version="1.0"?>
ovaj file ti ne treba. Editiraš samo `cms_page_form.xml`, Magento će ih na kraju sve mergati u jedan konačni file

2021-09-09 12:33 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +
`declare(strict_types=1);`

2021-09-09 12:33 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> + */
ne treba ti generični komentar. Slobodno ostavi bez komentara ako nemaš ništa relevantno napisati

2021-09-09 12:33 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +        foreach ($collection as $block) {
odakle si izvukao `$block` za ime varijable? Ja bi išao s `$item` ili `$postcode`

2021-09-09 12:33 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +        foreach ($collection as $block) {
CRUD metode na modelu su deprecated i ne bi ih se trebalo koristiti. Treba ići preko resource model ili repository

2021-09-13 06:11 UTC, ivanmatozan approved these changes

2021-09-14 10:28 UTC, tnikcevs approved these changes

2021-09-14 10:31 UTC, merged